package com.ceshiren;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static java.lang.Thread.sleep;

public class Searchtest1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    //driver = new ChromeDriver();
    //js = (JavascriptExecutor) driver;
    //vars = new HashMap<String, Object>();
    System.setProperty("webdriver.chrome.driver","D:\\chromedriver_win32\\chromedriver.exe");
    driver=new ChromeDriver();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void searchtest1() {

    driver.get("https://ceshiren.com/");
    try {
      sleep(1000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }

    driver.manage().window().setSize(new Dimension(1296, 705));
    try {
      sleep(1000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }

    //driver.findElement(By.id("search-term")).click(".d-icon-search");
    WebElement searchElement = driver.findElement(By.cssSelector(".d-icon-search"));
    searchElement.click();
    try {
      sleep(1000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }

    //driver.findElement(By.id("search-term")).sendKeys("selenium");
    WebElement inputElement = driver.findElement(By.id("search-term"));
    inputElement.sendKeys("selenium");
    try {
      sleep(1000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }

    WebElement allSearchEle = driver.findElement(By.cssSelector(".label-suffix"));
    allSearchEle.click();
    try {
      sleep(1000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }

    WebElement moreElement = driver.findElement(By.linkText("更多..."));
    moreElement.click();
    try {
      sleep(10000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
  }
}
